name: Single test

on: 
  workflow_dispatch:
  push:
    branches:
        - single-test

jobs:
  read-file:
    name: Read file and print
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        uses: actions/download-artifact@v4
        with:
            name: homework_pre
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: homework_pre
          path: math-homework.txt
  write-file:

